kind: Service
apiVersion: v1
metadata:
  name: beedemo-sa
  labels:
    net.beedemo.deploy.type: workshop
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: beedemo-sa
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: beedemo-sa-staging
  labels:
    net.beedemo.deploy.type: workshop
spec:
  replicas: 1
  template:
    metadata:
      name: beedemo-sa
      labels:
        net.beedemo.deploy.type: workshop
        app: beedemo-sa
        env: staging
    spec:
      serviceAccountName: cjoc
      containers:
      - name: beedemo-sa
        image: gcr.io/core-workshop/helloworld-nodejs:beedemo-sa-6
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
        imagePullPolicy: Always
        ports:
        - name: public
          containerPort: 8080
      securityContext:
        runAsUser: 1000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: beedemo-sa
  labels:
    net.beedemo.deploy.type: workshop
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /beedemo-sa/?(.*)
        backend:
          serviceName: beedemo-sa
          servicePort: 80
    host: staging.cb-sa.io
